version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - TENANT=${TENANT}
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - '5173:80'
    depends_on:
      - backend
